# This file describes the plugin
name: ajenti-vh
author: NamPNQ
email: nampnq@gmail.com
url: http://nampnq.cf
version: '0.1'
title: 'Websites'
icon: globe
# dependency on Core is required for UI plugins
dependencies:
    - !!python/object:aj.plugins.PluginDependency {
        plugin_name: core
    }
resources:
    - 'resources/js/module.coffee' # angular module init
    - 'resources/js/routing.coffee' # ngRoute config
    - 'resources/js/controllers/index.controller.coffee' # angular contrller
    - 'resources/partial/index.html' # view template
    - 'ng:ajenti.vh' # instructs ajenti to load Angular module 'ajenti.vh'
